version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - ./gradlew docker


artifacts:
  files:
    - 'build/libs/*'

cache:
  paths:
    - '/root/.gradle/wrapper/**/*'
    - '.gradle/**/*'
