version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - ./gradlew docker


artifacts:
  files:
    - 'build/libs/*'

cache:
  paths:
    - '/root/.gradle/wrapper/**/*'
    - '.gradle/**/*'
