#!/bin/sh
#
# Called by "git commit" with the name of the file that has the
# commit message, followed by the description of the commit
# message's source.  The hook's purpose is to edit the commit
# message file.  If the hook fails with a non-zero status,
# the commit is aborted.
#
# To enable this hook, rename this file to "prepare-commit-msg".

# The hook is being used here to prevent merges to master without a change to the version.

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

PROTECTED_BRANCH=master

BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')

if [ "${BRANCH_NAME}" == "${PROTECTED_BRANCH}" ] && [ "${COMMIT_SOURCE}" == "merge" ]
then
    # On the protected branch.  Check the diff for a changed version.
    NEW_VERSION_LINE=$(git --no-pager diff --cached --diff-filter=AM build.gradle | grep "^\+version\s*=")
    if [ -z "${NEW_VERSION_LINE}" ]
    then
        echo Denying commit to the \"${PROTECTED_BRANCH}\" branch.
        echo Please update the version in build.gradle before trying again.
        exit 1
    fi
fi

# Not on the protected branch.  Continue normally.
echo Allow commit to the \"${BRANCH_NAME}\" branch.  The project version *was* changed.
